version: '3.4'

networks:
  contentmanagement-network:

services: 
  frontend:
    image: kikinho92/frontend:v1
    ports:
      - "8005:80"
    networks:
      - contentmanagement-network
    depends_on:
      - sqlserver
  auth-api:
    image: kikinho92/auth-api:v2
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "8001:8001"
    networks:
      - contentmanagement-network
    depends_on:
      - sqlserver
  user-api:
    image: kikinho92/user-api:v1
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "8002:8002"
    networks:
      - contentmanagement-network
    depends_on:
      - sqlserver
  content-api:
    image: kikinho92/content-api:v1
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "8003:8003"
    networks:
      - contentmanagement-network
    depends_on:
      - sqlserver
  integration-api:
    image: kikinho92/integration-api:v1
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "8004:8004"
    networks:
      - contentmanagement-network
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Tfg.1234
      - ACCEPT_EULA=Y
    networks:
      contentmanagement-network:
    ports:
    - "1433:1433"

    