version: '3.4'

networks:
  contentmanagement-network:

services: 
  frontend:
    image: contentmanagement/frontend
    build:
      context: .
      dockerfile: ContentManagement-Frontend/Dockerfile
    ports:
      - "8005:80"
    networks:
      - contentmanagement-network
    depends_on:
      - sqlserver
  auth-api:
    image: contentmanagement/auth-api
    build:
      context: .
      dockerfile: 01. Auth/Service.Auth/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:8001"
    networks:
      - contentmanagement-network
    depends_on:
      - sqlserver
  user-api:
    image: contentmanagement/user-api
    build:
      context: .
      dockerfile: 02. User/Service.User/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8002:8002"
    networks:
      - contentmanagement-network
    depends_on:
      - sqlserver
  content-api:
    image: contentmanagement/content-api
    build:
      context: .
      dockerfile: 03. Content/Service.Content/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8003:8003"
    entrypoint: ["./wait-for-it.sh", "sqlserver:1433", "-t", "120", "--", "dotnet", "Service.Content.dll"]
    networks:
      - contentmanagement-network
    depends_on:
      - sqlserver
  integration-api:
    image: contentmanagement/integration-api
    build:
      context: .
      dockerfile: 04. Integration/Service.Integration/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8004:8004"
    networks:
      - contentmanagement-network
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Tfg.1234
      - ACCEPT_EULA=Y
    networks:
      contentmanagement-network:
    ports:
    - "1433:1433"

    