---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contentmanangement-auth-api
    spec:
      containers:
      - name: contentmanangement-auth-api
        image: kikinho92/contentmanangement-auth-api:latest
        ports:
        - containerPort: 8001
        env:
        - name: ASPNETCORE_URLS
          value: http://*:8001
  selector:
    matchLabels:
      app: contentmanangement-auth-api
---
apiVersion: v1
kind: Service
metadata:
  name: contentmanangement-auth-api
spec:
  type: ClusterIP
  ports:
  - port: 8001
  selector:
    app: contentmanangement-auth-api