---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contentmanangement-user-api
    spec:
      containers:
      - name: contentmanangement-user-api
        image: kikinho92/contentmanangement-user-api:latest
        ports:
        - containerPort: 8002
        env:
        - name: ASPNETCORE_URLS
          value: http://*:8002
  selector:
    matchLabels:
      app: contentmanangement-user-api
---
apiVersion: v1
kind: Service
metadata:
  name: contentmanangement-user-api
spec:
  type: ClusterIP
  ports:
  - port: 8002
  selector:
    app: contentmanangement-user-api