---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: integration-api
    spec:
      containers:
      - name: integration-api
        image: kikinho92/integration-api:k8s
        ports:
        - containerPort: 8004
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
  selector:
    matchLabels:
      app: integration-api
---
apiVersion: v1
kind: Service
metadata:
  name: integration-service
spec:
  type: ClusterIP
  ports:
  - port: 8004
  selector:
    app: integration