---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
      - name: content-api
        image: kikinho92/content-api:k8s
        ports:
        - containerPort: 8003
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
  selector:
    matchLabels:
      app: content-api
---
apiVersion: v1
kind: Service
metadata:
  name: content-service
spec:
  type: ClusterIP
  ports:
  - port: 8003
  selector:
    app: content-api