---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contentmanangement-integration-api
    spec:
      containers:
      - name: integration-api
        image: kikinho92/contentmanangement-integration-api:latest
        ports:
        - containerPort: 8004
        env:
        - name: ASPNETCORE_URLS
          value: http://*:8004
  selector:
    matchLabels:
      app: contentmanangement-integration-api
---
apiVersion: v1
kind: Service
metadata:
  name: contentmanangement-integration-api
spec:
  type: ClusterIP
  ports:
  - port: 8004
  selector:
    app: contentmanangement-integration-api