---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: kikinho92/user-api:k8s
        ports:
        - containerPort: 8002
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
  selector:
    matchLabels:
      app: user-api
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  ports:
  - port: 8002
  selector:
    app: user